# Generated by Django 5.2 on 2025-04-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_covidsymptomreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CovidSymptomReport',
        ),
    ]
